CREATE DATABASE IF NOT EXISTS smart_parking;
USE smart_parking;

CREATE TABLE IF NOT EXISTS USER (
  User_ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Contact_Info VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS VEHICLE (
  Vehicle_No VARCHAR(20) PRIMARY KEY,
  Model VARCHAR(100) NOT NULL,
  Type ENUM('Car', 'Bike', 'SUV', 'Truck') NOT NULL,
  Arrival_Time DATETIME DEFAULT CURRENT_TIMESTAMP,
  Exit_Time DATETIME,
  User_ID INT NOT NULL,
  FOREIGN KEY (User_ID) REFERENCES USER(User_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS STAFF (
  Staff_ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PARKING_SLOT (
  Slot_ID INT AUTO_INCREMENT PRIMARY KEY,
  Location VARCHAR(100) NOT NULL,
  Is_Occupied BOOLEAN DEFAULT FALSE,
  Staff_ID INT,
  FOREIGN KEY (Staff_ID) REFERENCES STAFF(Staff_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TICKET (
  Ticket_ID INT AUTO_INCREMENT PRIMARY KEY,
  Vehicle_No VARCHAR(20) NOT NULL,
  Slot_ID INT NOT NULL,
  FOREIGN KEY (Vehicle_No) REFERENCES VEHICLE(Vehicle_No) ON DELETE CASCADE,
  FOREIGN KEY (Slot_ID) REFERENCES PARKING_SLOT(Slot_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
  Trans_ID INT AUTO_INCREMENT PRIMARY KEY,
  Ticket_ID INT NOT NULL,
  Amount DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (Ticket_ID) REFERENCES TICKET(Ticket_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PAYMENT (
  Payment_ID INT AUTO_INCREMENT PRIMARY KEY,
  Trans_ID INT NOT NULL,
  Method VARCHAR(50) NOT NULL,
  Status ENUM('Success', 'Pending', 'Failed') DEFAULT 'Success',
  FOREIGN KEY (Trans_ID) REFERENCES TRANSACTIONS(Trans_ID) ON DELETE CASCADE
);

INSERT INTO STAFF (Name, Role) VALUES
  ('Alice Johnson', 'Manager'),
  ('Bob Smith', 'Attendant'),
  ('Carol White', 'Security');

INSERT INTO PARKING_SLOT (Location, Is_Occupied, Staff_ID) VALUES
  ('Block A - Slot 1', FALSE, 1),
  ('Block A - Slot 2', FALSE, 1),
  ('Block A - Slot 3', FALSE, 2),
  ('Block B - Slot 1', FALSE, 2),
  ('Block B - Slot 2', FALSE, 3),
  ('Block B - Slot 3', FALSE, 3),
  ('Block C - Slot 1', FALSE, 1),
  ('Block C - Slot 2', FALSE, 2),
  ('Block C - Slot 3', FALSE, 3),
  ('Block C - Slot 4', FALSE, 1);
